feat(install-oh-my-zsh): exits on error `set -e`

diff --git a/bin/sh/install-oh-my-zsh b/bin/sh/install-oh-my-zsh
--- a/bin/sh/install-oh-my-zsh
+++ b/bin/sh/install-oh-my-zsh
@@ -1,5 +1,8 @@
 #!/bin/zsh
 
+# exit on error
+set -e
+
 if [ -n "$ZSH" ] && [ -d "${ZSH}" ]; then
     echo "Oh-my-zsh already installed."
     . "$ZSH/tools/upgrade.sh"
